### ISSUE TITLE
Make Arch use primarly Its world API? 

### ISSUE THREAD

**Issue by genaray** [friflo/ECS.CSharp.Benchmark-common-use-cases#2]
You could replace archs Entity API with the worlds API in some places. E.g. the Get/Set Benchmark. This improves the Speed since there fewer lookups required. Not Sure If this is wanted tho ^^

**Comment by friflo** [comment]
hi @genaray 

I used the more performant world API in the Arch benchmarks where applicable.

- AddRemoveComponentsT1_Arch
- AddRemoveComponentsT5_Arch
- GetSetComponentsT1_Arch

Let me know if I missed a place.  
In Benchmark Setup()/Shutdown() I made no changes. These methods are not part of the measurement.

Commit: https://github.com/friflo/ECS.CSharp.Benchmark-common-use-cases/commit/5dfa6e4d643cbfe811a5bd2f5611ac158386210b

Before:

| Type                       | Mean           | Allocated |
|--------------------------- |---------------:|----------:|
| AddRemoveComponentsT1_Arch |    17,659.3 ns |   12000 B |
| AddRemoveComponentsT5_Arch |    38,343.4 ns |    8800 B |
| CreateEntityT1_Arch        | 3,748,030.9 ns |    2752 B |
| CreateEntityT3_Arch        | 4,001,060.2 ns |    2752 B |
| CreateWorld_Arch           |     5,484.4 ns |   37040 B |
| DeleteEntity_Arch          | 6,254,032.4 ns |    2752 B |
| GetSetComponentsT1_Arch    |       841.7 ns |         - |
| QueryT1_Arch               |       230.5 ns |         - |
| QueryT5_Arch               |       347.0 ns |         - |

After:

| Type                       | Mean           | Allocated |
|--------------------------- |---------------:|----------:|
| AddRemoveComponentsT1_Arch |    17,180.9 ns |   12000 B |
| AddRemoveComponentsT5_Arch |    38,627.4 ns |    8800 B |
| CreateEntityT1_Arch        | 3,729,714.1 ns |    2752 B |
| CreateEntityT3_Arch        | 4,042,495.7 ns |    2752 B |
| CreateWorld_Arch           |     5,498.1 ns |   37040 B |
| DeleteEntity_Arch          | 6,195,592.3 ns |    2752 B |
| GetSetComponentsT1_Arch    |       720.7 ns |         - |
| QueryT1_Arch               |       215.7 ns |         - |
| QueryT5_Arch               |       343.2 ns |         - |

**Comment by friflo** [comment]
Just updated the README benchmarks with the mentioned optimizations.

**Comment by genaray** [comment]
> Just updated the README benchmarks with the mentioned optimizations.

Thanks! Could you also mention somewhere that arch actually features events and relations? It does, events are inbuilt as a flag and relations are offered by an extension :)

**Comment by friflo** [comment]
Hi @genaray,

- will add benchmarks for relations and entity relationships using Arch.Relationships
- will probably add a note for events. Not sure. Have to think about it.  
  This benchmark is about what is available in the nuget package. Not what could be available if doing this or that ...  
  Can you add events to Arch nuget?  
  That will be appreciated by your users!

That note for events triggers me a little as it generates forks by promoting a disabled feature. 🤨  
GitHub & Google rank projects with many forks higher than project with less. If this is intentional its a clever move. 😎

**Comment by genaray** [comment]
Thanks! Its up to you if you want to benchmark those, i Just wanted to note that Arch officially has those supported aswell. In my opinion it just makes sense to note it somewhere or to make it a : (✅). 

Actually i did not know that GitHub Ranks Projects with many forks Higher. I just did not want these included by default since archs purpose is being bare minimal and enabling them by default is Not what everybody wants ^^

**Comment by friflo** [comment]
Ok. not everybody want events.

On thing I forgot to mention.  
All projects supporting events already have a performance penalty in benchmarks *add/remove components* and *create/delete entity* because their event callback handling is not free.  
This gives Arch currently a performance advantage in these benchmarks.

**Comment by friflo** [comment]
Just added relation benchmarks for Arch.
Will run / update benchmarks later this day.

**Comment by friflo** [comment]
Also added a note for events.
